/*
 * MapMatching.cc
 *
 *  Created on: Feb 8, 2017
 *      Author: liborio
 */

#include <MapMatching/MapMatching.h>

namespace Localization {

MapMatching::MapMatching() {
    // TODO Auto-generated constructor stub

}

//MapMatching::MapMatching(std::string route) {
//    // TODO Parse the path for the correct when needed
//
//    std::string routeFileName = "../localization/Graphs/out/"+route+".txt";
//    std::fstream fileGraph(routeFileName.c_str());
//    Edge edge;
//    Coord coord;
//    int i, totalCoords;
//
//    while(fileGraph >> edge.id >> totalCoords){
//
//        for (i = 0; i < totalCoords; i++){
//            fileGraph >> coord.x >> coord.y;
//            edge.shape.push_back(coord);
//        }
//
//        listEdges.push_back(edge);
//    }
//}

MapMatching::MapMatching(std::string route) {
    // TODO Parse the path for the correct when needed

    std::string routeFileName = "../localization/Graphs/out/"+route+".txt";
    std::fstream fileGraph(routeFileName.c_str());
    Edge edge;
    Coord coord;
    int i, totalCoords;

    /*while(fileGraph >> edge.id >> totalCoords){

        for (i = 0; i < totalCoords; i++){
            fileGraph >> coord.x >> coord.y;
            edge.shape.push_back(coord);
        }

        listEdges.push_back(edge);
    }*/

    if (route == "DMATEntranceExit" ){
        coord.x = 97.90; coord.y = 0.79;
        coordinates.push_back(coord);
        coord.x = 99.28; coord.y = 12.51;
        coordinates.push_back(coord);
        coord.x = 101.53; coord.y = 29.14;
        coordinates.push_back(coord);
        coord.x = 103.74; coord.y = 43.42;
        coordinates.push_back(coord);
        coord.x = 106.25; coord.y = 56.98;
        coordinates.push_back(coord);
        coord.x = 109.14; coord.y = 71.63;
        coordinates.push_back(coord);
        coord.x = 112.71; coord.y = 86.89;
        coordinates.push_back(coord);
        coord.x = 116.58; coord.y = 101.25;
        coordinates.push_back(coord);
        coord.x = 120.44; coord.y = 114.84;
        coordinates.push_back(coord);
        coord.x = 119.69; coord.y = 118.18;
        coordinates.push_back(coord);
        coord.x = 122.90; coord.y = 129.14;
        coordinates.push_back(coord);
        coord.x = 126.31; coord.y = 140.56;
        coordinates.push_back(coord);
        coord.x = 130.58; coord.y = 153.76;
        coordinates.push_back(coord);
        coord.x = 133.95; coord.y = 163.17;
        coordinates.push_back(coord);
        coord.x = 133.95; coord.y = 163.17;
        coordinates.push_back(coord);
        coord.x = 139.59; coord.y = 177.31;
        coordinates.push_back(coord);
        coord.x = 144.87; coord.y = 189.38;
        coordinates.push_back(coord);
        coord.x = 151.13; coord.y = 202.75;
        coordinates.push_back(coord);
        coord.x = 157.01; coord.y = 214.74;
        coordinates.push_back(coord);
        coord.x = 163.11; coord.y = 226.37;
        coordinates.push_back(coord);
        coord.x = 169.73; coord.y = 238.44;
        coordinates.push_back(coord);
        coord.x = 177.10; coord.y = 251.40;
        coordinates.push_back(coord);
        coord.x = 184.00; coord.y = 263.09;
        coordinates.push_back(coord);
        coord.x = 294.46; coord.y = 453.52;
        coordinates.push_back(coord);
        coord.x = 294.45; coord.y = 453.49;
        coordinates.push_back(coord);
        coord.x = 301.76; coord.y = 466.66;
        coordinates.push_back(coord);
        coord.x = 307.19; coord.y = 477.10;
        coordinates.push_back(coord);
        coord.x = 312.86; coord.y = 488.39;
        coordinates.push_back(coord);
        coord.x = 317.83; coord.y = 498.94;
        coordinates.push_back(coord);
        coord.x = 317.85; coord.y = 498.98;
        coordinates.push_back(coord);
        coord.x = 321.97; coord.y = 508.66;
        coordinates.push_back(coord);
        coord.x = 326.05; coord.y = 518.89;
        coordinates.push_back(coord);
        coord.x = 330.59; coord.y = 531.11;
        coordinates.push_back(coord);
        coord.x = 335.06; coord.y = 544.09;
        coordinates.push_back(coord);
        coord.x = 339.28; coord.y = 557.80;
        coordinates.push_back(coord);
        coord.x = 343.19; coord.y = 572.19;
        coordinates.push_back(coord);
        coord.x = 346.51; coord.y = 586.03;
        coordinates.push_back(coord);
        coord.x = 349.69; coord.y = 601.81;
        coordinates.push_back(coord);
        coord.x = 352.07; coord.y = 616.59;
        coordinates.push_back(coord);
        coord.x = 353.89; coord.y = 630.10;
        coordinates.push_back(coord);
        coord.x = 355.39; coord.y = 643.98;
        coordinates.push_back(coord);
        coord.x = 356.52; coord.y = 658.21;
        coordinates.push_back(coord);
        coord.x = 357.11; coord.y = 672.39;
        coordinates.push_back(coord);
        coord.x = 357.37; coord.y = 686.61;
        coordinates.push_back(coord);
        coord.x = 357.43; coord.y = 696.59;
        coordinates.push_back(coord);
        coord.x = 357.43; coord.y = 696.59;
        coordinates.push_back(coord);
        coord.x = 361.13; coord.y = 1093.02;
        coordinates.push_back(coord);
        coord.x = 361.13; coord.y = 1093.02;
        coordinates.push_back(coord);
        coord.x = 362.17; coord.y = 1221.23;
        coordinates.push_back(coord);
        coord.x = 362.17; coord.y = 1221.23;
        coordinates.push_back(coord);
        coord.x = 363.89; coord.y = 1436.34;
        coordinates.push_back(coord);
        coord.x = 363.89; coord.y = 1436.34;
        coordinates.push_back(coord);
        coord.x = 364.69; coord.y = 1523.37;
        coordinates.push_back(coord);
        coord.x = 364.69; coord.y = 1523.37;
        coordinates.push_back(coord);
        coord.x = 366.15; coord.y = 1666.76;
        coordinates.push_back(coord);
        coord.x = 366.15; coord.y = 1666.76;
        coordinates.push_back(coord);
        coord.x = 367.15; coord.y = 1775.12;
        coordinates.push_back(coord);
        coord.x = 367.67; coord.y = 1832.30;
        coordinates.push_back(coord);
        coord.x = 367.38; coord.y = 1847.58;
        coordinates.push_back(coord);
        coord.x = 366.20; coord.y = 1860.35;
        coordinates.push_back(coord);
        coord.x = 364.09; coord.y = 1871.90;
        coordinates.push_back(coord);
        coord.x = 360.11; coord.y = 1885.56;
        coordinates.push_back(coord);
        coord.x = 354.73; coord.y = 1897.66;
        coordinates.push_back(coord);
        coord.x = 348.18; coord.y = 1910.54;
        coordinates.push_back(coord);
        coord.x = 340.74; coord.y = 1922.30;
        coordinates.push_back(coord);
        coord.x = 332.72; coord.y = 1933.48;
        coordinates.push_back(coord);
        coord.x = 324.17; coord.y = 1943.59;
        coordinates.push_back(coord);
        coord.x = 314.41; coord.y = 1952.74;
        coordinates.push_back(coord);
        coord.x = 304.46; coord.y = 1960.52;
        coordinates.push_back(coord);
        coord.x = 293.11; coord.y = 1967.72;
        coordinates.push_back(coord);
        coord.x = 281.32; coord.y = 1973.55;
        coordinates.push_back(coord);
        coord.x = 268.75; coord.y = 1978.39;
        coordinates.push_back(coord);
        coord.x = 255.48; coord.y = 1982.36;
        coordinates.push_back(coord);
        coord.x = 242.34; coord.y = 1985.28;
        coordinates.push_back(coord);
        coord.x = 190.18; coord.y = 1996.48;
        coordinates.push_back(coord);
        coord.x = 171.85; coord.y = 2001.51;
        coordinates.push_back(coord);
        coord.x = 154.23; coord.y = 2008.03;
        coordinates.push_back(coord);
        coord.x = 137.72; coord.y = 2015.48;
        coordinates.push_back(coord);
        coord.x = 122.74; coord.y = 2024.00;
        coordinates.push_back(coord);
        coord.x = 107.83; coord.y = 2033.67;
        coordinates.push_back(coord);
        coord.x = 92.90; coord.y = 2044.15;
        coordinates.push_back(coord);
        coord.x = 78.63; coord.y = 2054.95;
        coordinates.push_back(coord);
        coord.x = 64.58; coord.y = 2066.40;
        coordinates.push_back(coord);
        coord.x = 51.68; coord.y = 2077.70;
        coordinates.push_back(coord);
        coord.x = 40.20; coord.y = 2087.92;
        coordinates.push_back(coord);
        coord.x = 26.46; coord.y = 2099.38;
        coordinates.push_back(coord);
        coord.x = -1.04; coord.y = 2121.89;
        coordinates.push_back(coord);
    }
    else{
        if(route == "DMATExitEntrance"){
            coord.x = 130.95; coord.y = 1974.69;
            coordinates.push_back(coord);
            coord.x = 145.22; coord.y = 1959.56;
            coordinates.push_back(coord);
            coord.x = 157.06; coord.y = 1948.21;
            coordinates.push_back(coord);
            coord.x = 171.01; coord.y = 1936.14;
            coordinates.push_back(coord);
            coord.x = 183.90; coord.y = 1925.75;
            coordinates.push_back(coord);
            coord.x = 199.33; coord.y = 1914.29;
            coordinates.push_back(coord);
            coord.x = 216.88; coord.y = 1901.82;
            coordinates.push_back(coord);
            coord.x = 231.25; coord.y = 1892.67;
            coordinates.push_back(coord);
            coord.x = 245.35; coord.y = 1883.60;
            coordinates.push_back(coord);
            coord.x = 259.01; coord.y = 1875.10;
            coordinates.push_back(coord);
            coord.x = 274.54; coord.y = 1865.93;
            coordinates.push_back(coord);
            coord.x = 289.88; coord.y = 1857.15;
            coordinates.push_back(coord);
            coord.x = 300.11; coord.y = 1850.40;
            coordinates.push_back(coord);
            coord.x = 310.02; coord.y = 1842.82;
            coordinates.push_back(coord);
            coord.x = 317.81; coord.y = 1835.36;
            coordinates.push_back(coord);
            coord.x = 325.61; coord.y = 1826.89;
            coordinates.push_back(coord);
            coord.x = 332.68; coord.y = 1817.82;
            coordinates.push_back(coord);
            coord.x = 339.38; coord.y = 1807.50;
            coordinates.push_back(coord);
            coord.x = 345.14; coord.y = 1796.82;
            coordinates.push_back(coord);
            coord.x = 349.92; coord.y = 1784.68;
            coordinates.push_back(coord);
            coord.x = 353.92; coord.y = 1772.98;
            coordinates.push_back(coord);
            coord.x = 356.73; coord.y = 1761.02;
            coordinates.push_back(coord);
            coord.x = 359.06; coord.y = 1748.05;
            coordinates.push_back(coord);
            coord.x = 360.20; coord.y = 1735.04;
            coordinates.push_back(coord);
            coord.x = 361.25; coord.y = 1667.06;
            coordinates.push_back(coord);
            coord.x = 361.25; coord.y = 1667.05;
            coordinates.push_back(coord);
            coord.x = 359.85; coord.y = 1523.36;
            coordinates.push_back(coord);
            coord.x = 359.85; coord.y = 1523.38;
            coordinates.push_back(coord);
            coord.x = 359.97; coord.y = 1436.45;
            coordinates.push_back(coord);
            coord.x = 359.98; coord.y = 1436.44;
            coordinates.push_back(coord);
            coord.x = 358.15; coord.y = 1221.28;
            coordinates.push_back(coord);
            coord.x = 358.15; coord.y = 1221.28;
            coordinates.push_back(coord);
            coord.x = 357.06; coord.y = 1093.05;
            coordinates.push_back(coord);
            coord.x = 357.06; coord.y = 1093.05;
            coordinates.push_back(coord);
            coord.x = 353.19; coord.y = 696.60;
            coordinates.push_back(coord);
            coord.x = 353.19; coord.y = 696.61;
            coordinates.push_back(coord);
            coord.x = 353.14; coord.y = 686.66;
            coordinates.push_back(coord);
            coord.x = 352.88; coord.y = 672.52;
            coordinates.push_back(coord);
            coord.x = 352.30; coord.y = 658.45;
            coordinates.push_back(coord);
            coord.x = 351.18; coord.y = 644.37;
            coordinates.push_back(coord);
            coord.x = 349.69; coord.y = 630.60;
            coordinates.push_back(coord);
            coord.x = 347.89; coord.y = 617.20;
            coordinates.push_back(coord);
            coord.x = 345.53; coord.y = 602.56;
            coordinates.push_back(coord);
            coord.x = 342.54; coord.y = 587.14;
            coordinates.push_back(coord);
            coord.x = 339.29; coord.y = 573.32;
            coordinates.push_back(coord);
            coord.x = 335.29; coord.y = 558.83;
            coordinates.push_back(coord);
            coord.x = 331.24; coord.y = 545.50;
            coordinates.push_back(coord);
            coord.x = 326.93; coord.y = 532.74;
            coordinates.push_back(coord);
            coord.x = 322.32; coord.y = 520.37;
            coordinates.push_back(coord);
            coord.x = 318.05; coord.y = 510.26;
            coordinates.push_back(coord);
            coord.x = 314.01; coord.y = 500.42;
            coordinates.push_back(coord);
            coord.x = 313.99; coord.y = 500.38;
            coordinates.push_back(coord);
            coord.x = 309.25; coord.y = 490.12;
            coordinates.push_back(coord);
            coord.x = 303.61; coord.y = 478.91;
            coordinates.push_back(coord);
            coord.x = 298.22; coord.y = 468.54;
            coordinates.push_back(coord);
            coord.x = 290.93; coord.y = 455.41;
            coordinates.push_back(coord);
            coord.x = 290.92; coord.y = 455.40;
            coordinates.push_back(coord);
            coord.x = 179.29; coord.y = 265.81;
            coordinates.push_back(coord);
            coord.x = 172.38; coord.y = 254.09;
            coordinates.push_back(coord);
            coord.x = 164.97; coord.y = 241.06;
            coordinates.push_back(coord);
            coord.x = 158.31; coord.y = 228.92;
            coordinates.push_back(coord);
            coord.x = 152.14; coord.y = 217.18;
            coordinates.push_back(coord);
            coord.x = 146.21; coord.y = 205.07;
            coordinates.push_back(coord);
            coord.x = 139.90; coord.y = 191.59;
            coordinates.push_back(coord);
            coord.x = 134.57; coord.y = 179.37;
            coordinates.push_back(coord);
            coord.x = 128.74; coord.y = 165.15;
            coordinates.push_back(coord);
            coord.x = 128.75; coord.y = 165.16;
            coordinates.push_back(coord);
            coord.x = 124.13; coord.y = 153.72;
            coordinates.push_back(coord);
            coord.x = 119.63; coord.y = 142.87;
            coordinates.push_back(coord);
            coord.x = 115.02; coord.y = 130.91;
            coordinates.push_back(coord);
            coord.x = 111.21; coord.y = 119.84;
            coordinates.push_back(coord);
            coord.x = 108.78; coord.y = 117.63;
            coordinates.push_back(coord);
            coord.x = 104.89; coord.y = 104.25;
            coordinates.push_back(coord);
            coord.x = 101.01; coord.y = 89.04;
            coordinates.push_back(coord);
            coord.x = 97.39; coord.y = 74.05;
            coordinates.push_back(coord);
            coord.x = 94.01; coord.y = 59.46;
            coordinates.push_back(coord);
            coord.x = 91.16; coord.y = 44.55;
            coordinates.push_back(coord);
            coord.x = 88.59; coord.y = 27.89;
            coordinates.push_back(coord);
            coord.x = 86.43; coord.y = 11.17;
            coordinates.push_back(coord);
            coord.x = 85.24; coord.y = -0.00;
            coordinates.push_back(coord);

        }
        else{
            if(route == "DPTExitEntrance"){
                coord.x = 1327.02;coord.y = 180.46;
                coordinates.push_back(coord);
                coord.x = 1355.93;coord.y = 255.69;
                coordinates.push_back(coord);
                coord.x = 1371.72;coord.y = 290.64;
                coordinates.push_back(coord);
                coord.x = 1384.91;coord.y = 315.16;
                coordinates.push_back(coord);
                coord.x = 1387.60;coord.y = 318.72;
                coordinates.push_back(coord);
                coord.x = 1419.52;coord.y = 349.69;
                coordinates.push_back(coord);
                coord.x = 1420.17;coord.y = 352.76;
                coordinates.push_back(coord);
                coord.x = 1448.99;coord.y = 385.19;
                coordinates.push_back(coord);
                coord.x = 1461.33;coord.y = 401.89;
                coordinates.push_back(coord);
                coord.x = 1470.95;coord.y = 417.70;
                coordinates.push_back(coord);
                coord.x = 1481.62;coord.y = 441.47;
                coordinates.push_back(coord);
                coord.x = 1487.27;coord.y = 465.48;
                coordinates.push_back(coord);
                coord.x = 1489.21;coord.y = 485.69;
                coordinates.push_back(coord);
                coord.x = 1487.97;coord.y = 505.79;
                coordinates.push_back(coord);
                coord.x = 1484.28;coord.y = 524.88;
                coordinates.push_back(coord);
                coord.x = 1475.11;coord.y = 550.14;
                coordinates.push_back(coord);
                coord.x = 1465.63;coord.y = 566.94;
                coordinates.push_back(coord);
                coord.x = 1456.15;coord.y = 578.51;
                coordinates.push_back(coord);
                coord.x = 1446.53;coord.y = 587.51;
                coordinates.push_back(coord);
                coord.x = 1423.67;coord.y = 605.87;
                coordinates.push_back(coord);
                coord.x = 1385.71;coord.y = 625.76;
                coordinates.push_back(coord);
                coord.x = 1339.69;coord.y = 645.18;
                coordinates.push_back(coord);
                coord.x = 1288.45;coord.y = 663.97;
                coordinates.push_back(coord);
                coord.x = 1236.88;coord.y = 682.29;
                coordinates.push_back(coord);
                coord.x = 1179.86;coord.y = 708.52;
                coordinates.push_back(coord);
                coord.x = 1179.44;coord.y = 708.74;
                coordinates.push_back(coord);
                coord.x = 1157.16;coord.y = 721.74;
                coordinates.push_back(coord);
                coord.x = 1115.96;coord.y = 743.45;
                coordinates.push_back(coord);
                coord.x = 1106.47;coord.y = 748.46;
                coordinates.push_back(coord);
                coord.x = 1069.04;coord.y = 774.61;
                coordinates.push_back(coord);
                coord.x = 1023.96;coord.y = 817.28;
                coordinates.push_back(coord);
                coord.x = 970.83;coord.y = 869.86;
                coordinates.push_back(coord);
                coord.x = 970.82;coord.y = 869.87;
                coordinates.push_back(coord);
                coord.x = 941.77;coord.y = 900.04;
                coordinates.push_back(coord);
                coord.x = 941.80;coord.y = 900.01;
                coordinates.push_back(coord);
                coord.x = 919.21;coord.y = 922.29;
                coordinates.push_back(coord);
                coord.x = 897.89;coord.y = 949.82;
                coordinates.push_back(coord);
                coord.x = 897.84;coord.y = 949.89;
                coordinates.push_back(coord);
                coord.x = 805.70;coord.y = 1083.95;
                coordinates.push_back(coord);
                coord.x = 792.67;coord.y = 1119.56;
                coordinates.push_back(coord);
                coord.x = 781.04;coord.y = 1151.44;
                coordinates.push_back(coord);
                coord.x = 758.10;coord.y = 1226.22;
                coordinates.push_back(coord);
                coord.x = 737.90;coord.y = 1304.03;
                coordinates.push_back(coord);
                coord.x = 727.39;coord.y = 1390.69;
                coordinates.push_back(coord);
                coord.x = 718.16;coord.y = 1444.48;
                coordinates.push_back(coord);
                coord.x = 708.18;coord.y = 1500.00;
                coordinates.push_back(coord);
                coord.x = 696.64;coord.y = 1564.20;
                coordinates.push_back(coord);
                coord.x = 610.11;coord.y = 1800.30;
                coordinates.push_back(coord);
                coord.x = 453.20;coord.y = 2234.65;
                coordinates.push_back(coord);
                coord.x = 436.25;coord.y = 2269.97;
                coordinates.push_back(coord);
                coord.x = 72.83;coord.y = 2649.46;
                coordinates.push_back(coord);
                coord.x = 43.09;coord.y = 2712.20;
                coordinates.push_back(coord);
                coord.x = 16.54;coord.y = 2805.58;
                coordinates.push_back(coord);
                coord.x = 2.57;coord.y = 3019.12;
                coordinates.push_back(coord);
                coord.x = -1.65;coord.y = 3609.34;
                coordinates.push_back(coord);
                coord.x = 37.61;coord.y = 3858.09;
                coordinates.push_back(coord);
                coord.x = 85.25;coord.y = 4207.80;
                coordinates.push_back(coord);
                coord.x = 97.58;coord.y = 4332.27;
                coordinates.push_back(coord);
                coord.x = 130.90;coord.y = 4615.73;
                coordinates.push_back(coord);
                coord.x = 137.72;coord.y = 4720.10;
                coordinates.push_back(coord);
                coord.x = 157.17;coord.y = 4919.25;
                coordinates.push_back(coord);
                coord.x = 169.08;coord.y = 4960.96;
                coordinates.push_back(coord);
                coord.x = 181.67;coord.y = 5011.00;
                coordinates.push_back(coord);
                coord.x = 226.46;coord.y = 5143.33;
                coordinates.push_back(coord);
                coord.x = 226.47;coord.y = 5143.38;
                coordinates.push_back(coord);
                coord.x = 230.77;coord.y = 5157.85;
                coordinates.push_back(coord);
                coord.x = 246.08;coord.y = 5196.38;
                coordinates.push_back(coord);
                coord.x = 272.48;coord.y = 5264.22;
                coordinates.push_back(coord);
                coord.x = 275.12;coord.y = 5266.20;
                coordinates.push_back(coord);
                coord.x = 318.48;coord.y = 5360.04;
                coordinates.push_back(coord);
                coord.x = 392.76;coord.y = 5502.57;
                coordinates.push_back(coord);
                coord.x = 530.65;coord.y = 5763.89;
                coordinates.push_back(coord);
                coord.x = 530.65;coord.y = 5763.89;
                coordinates.push_back(coord);
                coord.x = 814.34;coord.y = 6286.34;
                coordinates.push_back(coord);
                coord.x = 814.28;coord.y = 6289.74;
                coordinates.push_back(coord);
                coord.x = 856.52;coord.y = 6370.93;
                coordinates.push_back(coord);
                coord.x = 881.41;coord.y = 6423.61;
                coordinates.push_back(coord);
                coord.x = 919.78;coord.y = 6509.43;
                coordinates.push_back(coord);
                coord.x = 970.76;coord.y = 6632.01;
                coordinates.push_back(coord);
                coord.x = 987.79;coord.y = 6677.42;
                coordinates.push_back(coord);
                coord.x = 1007.89;coord.y = 6731.43;
                coordinates.push_back(coord);
                coord.x = 1032.88;coord.y = 6803.98;
                coordinates.push_back(coord);
                coord.x = 1070.01;coord.y = 6921.41;
                coordinates.push_back(coord);
                coord.x = 1112.05;coord.y = 7074.59;
                coordinates.push_back(coord);
                coord.x = 1143.15;coord.y = 7186.13;
                coordinates.push_back(coord);
                coord.x = 1151.57;coord.y = 7214.94;
                coordinates.push_back(coord);
                coord.x = 1200.72;coord.y = 7390.95;
                coordinates.push_back(coord);
                coord.x = 1252.94;coord.y = 7570.21;
                coordinates.push_back(coord);

            }
            else{
                if(route == "DPTExitEntrance"){
                    coord.x = 1053.54; coord.y = 6772.08;
                    coordinates.push_back(coord);
                    coord.x = 1043.91; coord.y = 6741.15;
                    coordinates.push_back(coord);
                    coord.x = 1025.16; coord.y = 6692.20;
                    coordinates.push_back(coord);
                    coord.x = 1006.30; coord.y = 6640.14;
                    coordinates.push_back(coord);
                    coord.x = 980.09; coord.y = 6574.98;
                    coordinates.push_back(coord);
                    coord.x = 964.23; coord.y = 6539.09;
                    coordinates.push_back(coord);
                    coord.x = 950.86; coord.y = 6507.44;
                    coordinates.push_back(coord);
                    coord.x = 929.45; coord.y = 6462.44;
                    coordinates.push_back(coord);
                    coord.x = 891.92; coord.y = 6384.41;
                    coordinates.push_back(coord);
                    coord.x = 832.11; coord.y = 6276.15;
                    coordinates.push_back(coord);
                    coord.x = 832.03; coord.y = 6275.99;
                    coordinates.push_back(coord);
                    coord.x = 821.95; coord.y = 6251.62;
                    coordinates.push_back(coord);
                    coord.x = 819.36; coord.y = 6250.00;
                    coordinates.push_back(coord);
                    coord.x = 782.25; coord.y = 6180.92;
                    coordinates.push_back(coord);
                    coord.x = 639.35; coord.y = 5908.50;
                    coordinates.push_back(coord);
                    coord.x = 639.35; coord.y = 5908.50;
                    coordinates.push_back(coord);
                    coord.x = 529.30; coord.y = 5702.09;
                    coordinates.push_back(coord);
                    coord.x = 504.68; coord.y = 5655.55;
                    coordinates.push_back(coord);
                    coord.x = 504.68; coord.y = 5655.55;
                    coordinates.push_back(coord);
                    coord.x = 414.26; coord.y = 5493.14;
                    coordinates.push_back(coord);
                    coord.x = 414.26; coord.y = 5493.14;
                    coordinates.push_back(coord);
                    coord.x = 298.30; coord.y = 5259.71;
                    coordinates.push_back(coord);
                    coord.x = 298.30; coord.y = 5259.71;
                    coordinates.push_back(coord);
                    coord.x = 271.44; coord.y = 5205.63;
                    coordinates.push_back(coord);
                    coord.x = 271.90; coord.y = 5202.62;
                    coordinates.push_back(coord);
                    coord.x = 260.64; coord.y = 5174.04;
                    coordinates.push_back(coord);
                    coord.x = 227.35; coord.y = 5087.00;
                    coordinates.push_back(coord);
                    coord.x = 223.60; coord.y = 5075.62;
                    coordinates.push_back(coord);
                    coord.x = 223.61; coord.y = 5075.65;
                    coordinates.push_back(coord);
                    coord.x = 197.98; coord.y = 4993.70;
                    coordinates.push_back(coord);
                    coord.x = 177.31; coord.y = 4918.43;
                    coordinates.push_back(coord);
                    coord.x = 157.72; coord.y = 4644.73;
                    coordinates.push_back(coord);
                    coord.x = 130.36; coord.y = 4428.40;
                    coordinates.push_back(coord);
                    coord.x = 116.95; coord.y = 4329.30;
                    coordinates.push_back(coord);
                    coord.x = 105.43; coord.y = 4213.76;
                    coordinates.push_back(coord);
                    coord.x = 18.77; coord.y = 3609.76;
                    coordinates.push_back(coord);
                    coord.x = 20.14; coord.y = 3019.81;
                    coordinates.push_back(coord);
                    coord.x = 39.67; coord.y = 2809.79;
                    coordinates.push_back(coord);
                    coord.x = 65.96; coord.y = 2719.78;
                    coordinates.push_back(coord);
                    coord.x = 89.56; coord.y = 2660.41;
                    coordinates.push_back(coord);
                    coord.x = 452.89; coord.y = 2281.01;
                    coordinates.push_back(coord);
                    coord.x = 468.44; coord.y = 2254.10;
                    coordinates.push_back(coord);
                    coord.x = 474.30; coord.y = 2242.62;
                    coordinates.push_back(coord);
                    coord.x = 632.54; coord.y = 1808.29;
                    coordinates.push_back(coord);
                    coord.x = 659.03; coord.y = 1737.19;
                    coordinates.push_back(coord);
                    coord.x = 695.25; coord.y = 1647.59;
                    coordinates.push_back(coord);
                    coord.x = 721.17; coord.y = 1571.92;
                    coordinates.push_back(coord);
                    coord.x = 731.39; coord.y = 1514.15;
                    coordinates.push_back(coord);
                    coord.x = 744.48; coord.y = 1440.19;
                    coordinates.push_back(coord);
                    coord.x = 751.09; coord.y = 1380.44;
                    coordinates.push_back(coord);
                    coord.x = 754.56; coord.y = 1327.87;
                    coordinates.push_back(coord);
                    coord.x = 763.72; coord.y = 1275.58;
                    coordinates.push_back(coord);
                    coord.x = 775.88; coord.y = 1219.16;
                    coordinates.push_back(coord);
                    coord.x = 791.70; coord.y = 1178.58;
                    coordinates.push_back(coord);
                    coord.x = 838.48; coord.y = 1076.44;
                    coordinates.push_back(coord);
                    coord.x = 923.93; coord.y = 947.02;
                    coordinates.push_back(coord);
                    coord.x = 923.96; coord.y = 946.98;
                    coordinates.push_back(coord);
                    coord.x = 937.74; coord.y = 927.67;
                    coordinates.push_back(coord);
                    coord.x = 954.10; coord.y = 909.18;
                    coordinates.push_back(coord);
                    coord.x = 954.24; coord.y = 909.03;
                    coordinates.push_back(coord);
                    coord.x = 982.92; coord.y = 879.62;
                    coordinates.push_back(coord);
                    coord.x = 983.07; coord.y = 879.47;
                    coordinates.push_back(coord);
                    coord.x = 1023.11; coord.y = 842.24;
                    coordinates.push_back(coord);
                    coord.x = 1071.66; coord.y = 806.91;
                    coordinates.push_back(coord);
                    coord.x = 1163.31; coord.y = 751.48;
                    coordinates.push_back(coord);
                    coord.x = 1217.24; coord.y = 724.41;
                    coordinates.push_back(coord);
                    coord.x = 1227.60; coord.y = 720.02;
                    coordinates.push_back(coord);
                    coord.x = 1278.93; coord.y = 695.08;
                    coordinates.push_back(coord);
                    coord.x = 1358.82; coord.y = 658.81;
                    coordinates.push_back(coord);
                    coord.x = 1406.97; coord.y = 637.98;
                    coordinates.push_back(coord);
                    coord.x = 1429.39; coord.y = 625.75;
                    coordinates.push_back(coord);
                    coord.x = 1446.68; coord.y = 614.02;
                    coordinates.push_back(coord);
                    coord.x = 1466.91; coord.y = 596.00;
                    coordinates.push_back(coord);
                    coord.x = 1480.75; coord.y = 579.66;
                    coordinates.push_back(coord);
                    coord.x = 1490.58; coord.y = 565.46;
                    coordinates.push_back(coord);
                    coord.x = 1498.54; coord.y = 546.89;
                    coordinates.push_back(coord);
                    coord.x = 1503.93; coord.y = 527.72;
                    coordinates.push_back(coord);
                    coord.x = 1507.93; coord.y = 508.26;
                    coordinates.push_back(coord);
                    coord.x = 1509.64; coord.y = 488.18;
                    coordinates.push_back(coord);
                    coord.x = 1508.17; coord.y = 462.41;
                    coordinates.push_back(coord);
                    coord.x = 1503.15; coord.y = 438.68;
                    coordinates.push_back(coord);
                    coord.x = 1491.42; coord.y = 412.65;
                    coordinates.push_back(coord);
                    coord.x = 1476.48; coord.y = 389.19;
                    coordinates.push_back(coord);
                    coord.x = 1476.01; coord.y = 388.57;
                    coordinates.push_back(coord);
                    coord.x = 1407.11; coord.y = 311.07;
                    coordinates.push_back(coord);
                }
                else{
                    if(route == "RCLTEntranceExit"){
                        coord.x = 863.91; coord.y = 547.54;
                        coordinates.push_back(coord);
                        coord.x = 915.82; coord.y = 556.20;
                        coordinates.push_back(coord);
                        coord.x = 958.40; coord.y = 563.30;
                        coordinates.push_back(coord);
                        coord.x = 990.68; coord.y = 568.69;
                        coordinates.push_back(coord);
                        coord.x = 1008.80; coord.y = 570.53;
                        coordinates.push_back(coord);
                        coord.x = 1009.69; coord.y = 570.39;
                        coordinates.push_back(coord);
                        coord.x = 1065.69; coord.y = 579.36;
                        coordinates.push_back(coord);
                        coord.x = 1133.67; coord.y = 584.89;
                        coordinates.push_back(coord);
                        coord.x = 1136.65; coord.y = 585.20;
                        coordinates.push_back(coord);
                        coord.x = 1146.28; coord.y = 586.40;
                        coordinates.push_back(coord);
                        coord.x = 1196.70; coord.y = 593.63;
                        coordinates.push_back(coord);
                        coord.x = 1196.67; coord.y = 593.63;
                        coordinates.push_back(coord);
                        coord.x = 1341.68; coord.y = 616.79;
                        coordinates.push_back(coord);
                        coord.x = 1341.66; coord.y = 616.79;
                        coordinates.push_back(coord);
                        coord.x = 1874.63; coord.y = 706.47;
                        coordinates.push_back(coord);
                        coord.x = 1919.70; coord.y = 714.05;
                        coordinates.push_back(coord);
                        coord.x = 1919.85; coord.y = 714.08;
                        coordinates.push_back(coord);
                        coord.x = 1933.37; coord.y = 716.90;
                        coordinates.push_back(coord);
                        coord.x = 1957.47; coord.y = 723.63;
                        coordinates.push_back(coord);
                        coord.x = 1997.46; coord.y = 734.87;
                        coordinates.push_back(coord);
                        coord.x = 1999.45; coord.y = 736.05;
                        coordinates.push_back(coord);
                        coord.x = 2015.62; coord.y = 738.73;
                        coordinates.push_back(coord);
                        coord.x = 2053.61; coord.y = 745.91;
                        coordinates.push_back(coord);
                        coord.x = 2059.55; coord.y = 746.96;
                        coordinates.push_back(coord);
                        coord.x = 2112.49; coord.y = 755.80;
                        coordinates.push_back(coord);
                        coord.x = 2118.63; coord.y = 756.82;
                        coordinates.push_back(coord);
                        coord.x = 2144.38; coord.y = 761.00;
                        coordinates.push_back(coord);
                        coord.x = 2160.27; coord.y = 763.59;
                        coordinates.push_back(coord);
                        coord.x = 2226.22; coord.y = 774.31;
                        coordinates.push_back(coord);
                        coord.x = 2289.90; coord.y = 784.57;
                        coordinates.push_back(coord);
                        coord.x = 2295.99; coord.y = 785.57;
                        coordinates.push_back(coord);
                        coord.x = 2305.59; coord.y = 787.18;
                        coordinates.push_back(coord);
                    }
                    else{
                        if(route == "RCLTExitEntrance"){
                            coord.x = 2305.05;coord.y = 790.44;
                            coordinates.push_back(coord);
                            coord.x = 2295.45;coord.y = 788.83;
                            coordinates.push_back(coord);
                            coord.x = 2289.38;coord.y = 787.83;
                            coordinates.push_back(coord);
                            coord.x = 2225.69;coord.y = 777.57;
                            coordinates.push_back(coord);
                            coord.x = 2159.74;coord.y = 766.84;
                            coordinates.push_back(coord);
                            coord.x = 2143.85;coord.y = 764.26;
                            coordinates.push_back(coord);
                            coord.x = 2118.10;coord.y = 760.07;
                            coordinates.push_back(coord);
                            coord.x = 2111.95;coord.y = 759.06;
                            coordinates.push_back(coord);
                            coord.x = 2059.00;coord.y = 750.21;
                            coordinates.push_back(coord);
                            coord.x = 2053.00;coord.y = 749.15;
                            coordinates.push_back(coord);
                            coord.x = 2015.01;coord.y = 741.97;
                            coordinates.push_back(coord);
                            coord.x = 1996.84;coord.y = 740.82;
                            coordinates.push_back(coord);
                            coord.x = 1939.21;coord.y = 725.57;
                            coordinates.push_back(coord);
                            coord.x = 1930.67;coord.y = 722.83;
                            coordinates.push_back(coord);
                            coord.x = 1919.41;coord.y = 719.30;
                            coordinates.push_back(coord);
                            coord.x = 1918.75;coord.y = 719.14;
                            coordinates.push_back(coord);
                            coord.x = 1873.79;coord.y = 711.63;
                            coordinates.push_back(coord);
                            coord.x = 1341.41;coord.y = 622.56;
                            coordinates.push_back(coord);
                            coord.x = 1341.40;coord.y = 622.56;
                            coordinates.push_back(coord);
                            coord.x = 1195.41;coord.y = 599.30;
                            coordinates.push_back(coord);
                            coord.x = 1195.41;coord.y = 599.30;
                            coordinates.push_back(coord);
                            coord.x = 1145.33;coord.y = 591.69;
                            coordinates.push_back(coord);
                            coord.x = 1135.56;coord.y = 590.48;
                            coordinates.push_back(coord);
                            coord.x = 1065.26;coord.y = 583.62;
                            coordinates.push_back(coord);
                            coord.x = 1046.95;coord.y = 580.67;
                            coordinates.push_back(coord);
                            coord.x = 1008.83;coord.y = 574.54;
                            coordinates.push_back(coord);
                            coord.x = 1008.41;coord.y = 574.38;
                            coordinates.push_back(coord);
                            coord.x = 989.59;coord.y = 575.20;
                            coordinates.push_back(coord);
                            coord.x = 957.32;coord.y = 569.81;
                            coordinates.push_back(coord);
                            coord.x = 914.74;coord.y = 562.71;
                            coordinates.push_back(coord);
                            coord.x = 862.83;coord.y = 554.05;
                            coordinates.push_back(coord);
                        }
                        else{
                            if(route == "RIO450EntranceExit"){
                                coord.x = 3678.24; coord.y = -0.00;
                                coordinates.push_back(coord);
                                coord.x = 3673.52; coord.y = 14.20;
                                coordinates.push_back(coord);
                                coord.x = 3666.01; coord.y = 35.19;
                                coordinates.push_back(coord);
                                coord.x = 3660.93; coord.y = 49.42;
                                coordinates.push_back(coord);
                                coord.x = 3656.17; coord.y = 64.11;
                                coordinates.push_back(coord);
                                coord.x = 3656.17; coord.y = 64.11;
                                coordinates.push_back(coord);
                                coord.x = 3654.91; coord.y = 68.38;
                                coordinates.push_back(coord);
                                coord.x = 3654.91; coord.y = 68.38;
                                coordinates.push_back(coord);
                                coord.x = 3653.84; coord.y = 72.05;
                                coordinates.push_back(coord);
                                coord.x = 3653.84; coord.y = 72.05;
                                coordinates.push_back(coord);
                                coord.x = 3651.22; coord.y = 80.95;
                                coordinates.push_back(coord);
                                coord.x = 3639.60; coord.y = 115.73;
                                coordinates.push_back(coord);
                                coord.x = 3615.24; coord.y = 193.60;
                                coordinates.push_back(coord);
                                coord.x = 3615.24; coord.y = 193.60;
                                coordinates.push_back(coord);
                                coord.x = 3613.78; coord.y = 197.86;
                                coordinates.push_back(coord);
                                coord.x = 3613.78; coord.y = 197.86;
                                coordinates.push_back(coord);
                                coord.x = 3611.12; coord.y = 206.67;
                                coordinates.push_back(coord);
                                coord.x = 3578.23; coord.y = 309.40;
                                coordinates.push_back(coord);
                                coord.x = 3578.23; coord.y = 309.40;
                                coordinates.push_back(coord);
                                coord.x = 3576.84; coord.y = 314.57;
                                coordinates.push_back(coord);
                                coord.x = 3576.73; coord.y = 314.93;
                                coordinates.push_back(coord);
                                coord.x = 3571.41; coord.y = 330.07;
                                coordinates.push_back(coord);
                                coord.x = 3557.77; coord.y = 372.06;
                                coordinates.push_back(coord);
                                coord.x = 3555.30; coord.y = 374.42;
                                coordinates.push_back(coord);
                                coord.x = 3551.75; coord.y = 386.16;
                                coordinates.push_back(coord);
                                coord.x = 3545.61; coord.y = 402.65;
                                coordinates.push_back(coord);
                                coord.x = 3545.60; coord.y = 402.66;
                                coordinates.push_back(coord);
                                coord.x = 3526.33; coord.y = 460.72;
                                coordinates.push_back(coord);
                                coord.x = 3499.30; coord.y = 501.24;
                                coordinates.push_back(coord);
                                coord.x = 3499.30; coord.y = 501.24;
                                coordinates.push_back(coord);
                                coord.x = 3463.15; coord.y = 555.59;
                                coordinates.push_back(coord);
                                coord.x = 3457.32; coord.y = 564.36;
                                coordinates.push_back(coord);
                                coord.x = 3441.51; coord.y = 588.12;
                                coordinates.push_back(coord);
                                coord.x = 3441.51; coord.y = 588.12;
                                coordinates.push_back(coord);
                                coord.x = 3438.28; coord.y = 592.96;
                                coordinates.push_back(coord);
                                coord.x = 3424.82; coord.y = 612.39;
                                coordinates.push_back(coord);
                                coord.x = 3424.82; coord.y = 612.40;
                                coordinates.push_back(coord);
                                coord.x = 3421.97; coord.y = 616.67;
                                coordinates.push_back(coord);
                                coord.x = 3416.38; coord.y = 625.94;
                                coordinates.push_back(coord);
                                coord.x = 3404.57; coord.y = 649.88;
                                coordinates.push_back(coord);
                                coord.x = 3404.32; coord.y = 650.44;
                                coordinates.push_back(coord);
                                coord.x = 3402.36; coord.y = 655.28;
                                coordinates.push_back(coord);
                                coord.x = 3402.12; coord.y = 655.80;
                                coordinates.push_back(coord);
                                coord.x = 3397.16; coord.y = 664.88;
                                coordinates.push_back(coord);
                                coord.x = 3395.09; coord.y = 668.77;
                                coordinates.push_back(coord);
                                coord.x = 3394.79; coord.y = 669.27;
                                coordinates.push_back(coord);
                                coord.x = 3356.42; coord.y = 724.62;
                                coordinates.push_back(coord);
                                coord.x = 3356.27; coord.y = 724.83;
                                coordinates.push_back(coord);
                                coord.x = 3353.40; coord.y = 728.53;
                                coordinates.push_back(coord);
                                coord.x = 3353.40; coord.y = 728.53;
                                coordinates.push_back(coord);
                                coord.x = 3349.58; coord.y = 733.45;
                                coordinates.push_back(coord);
                                coord.x = 3329.07; coord.y = 762.26;
                                coordinates.push_back(coord);
                                coord.x = 3310.81; coord.y = 790.19;
                                coordinates.push_back(coord);
                                coord.x = 3275.30; coord.y = 839.65;
                                coordinates.push_back(coord);
                                coord.x = 3275.29; coord.y = 839.65;
                                coordinates.push_back(coord);
                                coord.x = 3272.78; coord.y = 843.34;
                                coordinates.push_back(coord);
                                coord.x = 3272.55; coord.y = 843.69;
                                coordinates.push_back(coord);
                                coord.x = 3270.67; coord.y = 846.77;
                                coordinates.push_back(coord);
                                coord.x = 3243.58; coord.y = 890.78;
                                coordinates.push_back(coord);
                                coord.x = 3243.57; coord.y = 890.79;
                                coordinates.push_back(coord);
                                coord.x = 3241.20; coord.y = 894.73;
                                coordinates.push_back(coord);
                                coord.x = 3241.21; coord.y = 894.72;
                                coordinates.push_back(coord);
                                coord.x = 3239.25; coord.y = 897.94;
                                coordinates.push_back(coord);
                                coord.x = 3236.58; coord.y = 902.25;
                                coordinates.push_back(coord);
                                coord.x = 3224.77; coord.y = 922.74;
                                coordinates.push_back(coord);
                                coord.x = 3212.89; coord.y = 949.54;
                                coordinates.push_back(coord);
                                coord.x = 3204.89; coord.y = 968.95;
                                coordinates.push_back(coord);
                                coord.x = 3185.59; coord.y = 1015.72;
                                coordinates.push_back(coord);
                                coord.x = 3185.59; coord.y = 1015.73;
                                coordinates.push_back(coord);
                                coord.x = 3183.67; coord.y = 1020.80;
                                coordinates.push_back(coord);
                                coord.x = 3183.67; coord.y = 1020.80;
                                coordinates.push_back(coord);
                                coord.x = 3174.83; coord.y = 1044.29;
                                coordinates.push_back(coord);
                                coord.x = 3174.63; coord.y = 1044.87;
                                coordinates.push_back(coord);
                                coord.x = 3165.08; coord.y = 1077.47;
                                coordinates.push_back(coord);
                                coord.x = 3164.28; coord.y = 1080.36;
                                coordinates.push_back(coord);
                                coord.x = 3148.71; coord.y = 1141.37;
                                coordinates.push_back(coord);
                                coord.x = 3135.75; coord.y = 1210.48;
                                coordinates.push_back(coord);
                                coord.x = 3135.69; coord.y = 1210.87;
                                coordinates.push_back(coord);
                                coord.x = 3134.08; coord.y = 1226.23;
                                coordinates.push_back(coord);
                                coord.x = 3135.43; coord.y = 1229.38;
                                coordinates.push_back(coord);
                                coord.x = 3126.92; coord.y = 1323.29;
                                coordinates.push_back(coord);
                                coord.x = 3125.36; coord.y = 1332.37;
                                coordinates.push_back(coord);
                                coord.x = 3122.85; coord.y = 1342.88;
                                coordinates.push_back(coord);
                                coord.x = 3119.68; coord.y = 1353.41;
                                coordinates.push_back(coord);
                                coord.x = 3114.56; coord.y = 1368.25;
                                coordinates.push_back(coord);
                                coord.x = 3109.46; coord.y = 1378.17;
                                coordinates.push_back(coord);
                                coord.x = 3104.23; coord.y = 1386.95;
                                coordinates.push_back(coord);
                                coord.x = 3097.89; coord.y = 1394.73;
                                coordinates.push_back(coord);
                                coord.x = 3089.82; coord.y = 1403.33;
                                coordinates.push_back(coord);
                                coord.x = 3081.40; coord.y = 1409.76;
                                coordinates.push_back(coord);
                                coord.x = 3070.05; coord.y = 1417.43;
                                coordinates.push_back(coord);
                                coord.x = 3050.36; coord.y = 1428.35;
                                coordinates.push_back(coord);
                                coord.x = 3036.03; coord.y = 1434.75;
                                coordinates.push_back(coord);
                                coord.x = 3026.28; coord.y = 1438.89;
                                coordinates.push_back(coord);
                                coord.x = 3015.53; coord.y = 1443.52;
                                coordinates.push_back(coord);
                                coord.x = 3005.79; coord.y = 1447.96;
                                coordinates.push_back(coord);
                                coord.x = 2991.05; coord.y = 1452.18;
                                coordinates.push_back(coord);
                                coord.x = 2977.12; coord.y = 1454.51;
                                coordinates.push_back(coord);
                                coord.x = 2964.05; coord.y = 1456.45;
                                coordinates.push_back(coord);
                                coord.x = 2763.08; coord.y = 1472.78;
                                coordinates.push_back(coord);
                                coord.x = 2724.57; coord.y = 1476.59;
                                coordinates.push_back(coord);
                                coord.x = 2703.53; coord.y = 1479.95;
                                coordinates.push_back(coord);
                                coord.x = 2680.15; coord.y = 1484.89;
                                coordinates.push_back(coord);
                                coord.x = 2370.95; coord.y = 1610.15;
                                coordinates.push_back(coord);
                                coord.x = 1979.29; coord.y = 1758.79;
                                coordinates.push_back(coord);
                                coord.x = 1975.96; coord.y = 1758.24;
                                coordinates.push_back(coord);
                                coord.x = 1841.93; coord.y = 1804.93;
                                coordinates.push_back(coord);
                                coord.x = 1761.88; coord.y = 1837.10;
                                coordinates.push_back(coord);
                                coord.x = 1759.89; coord.y = 1839.77;
                                coordinates.push_back(coord);
                                coord.x = 1732.43; coord.y = 1852.62;
                                coordinates.push_back(coord);
                                coord.x = 1732.17; coord.y = 1852.75;
                                coordinates.push_back(coord);
                                coord.x = 1721.93; coord.y = 1858.30;
                                coordinates.push_back(coord);
                                coord.x = 1702.84; coord.y = 1871.51;
                                coordinates.push_back(coord);
                                coord.x = 1693.28; coord.y = 1876.50;
                                coordinates.push_back(coord);
                                coord.x = 1683.37; coord.y = 1879.09;
                                coordinates.push_back(coord);
                                coord.x = 1671.18; coord.y = 1880.63;
                                coordinates.push_back(coord);
                                coord.x = 1654.29; coord.y = 1879.95;
                                coordinates.push_back(coord);
                                coord.x = 1627.45; coord.y = 1874.68;
                                coordinates.push_back(coord);
                                coord.x = 1487.91; coord.y = 1877.22;
                                coordinates.push_back(coord);
                                coord.x = 1484.92; coord.y = 1875.70;
                                coordinates.push_back(coord);
                                coord.x = 1424.70; coord.y = 1879.63;
                                coordinates.push_back(coord);
                                coord.x = 1424.74; coord.y = 1879.62;
                                coordinates.push_back(coord);
                                coord.x = 1343.01; coord.y = 1883.04;
                                coordinates.push_back(coord);
                                coord.x = 1328.01; coord.y = 1882.33;
                                coordinates.push_back(coord);
                                coord.x = 1313.96; coord.y = 1878.52;
                                coordinates.push_back(coord);
                                coord.x = 1209.13; coord.y = 1836.28;
                                coordinates.push_back(coord);
                                coord.x = 919.67; coord.y = 1711.10;
                                coordinates.push_back(coord);
                                coord.x = 902.99; coord.y = 1704.74;
                                coordinates.push_back(coord);
                                coord.x = 862.74; coord.y = 1700.21;
                                coordinates.push_back(coord);
                                coord.x = 845.42; coord.y = 1699.43;
                                coordinates.push_back(coord);
                                coord.x = 808.04; coord.y = 1691.82;
                                coordinates.push_back(coord);
                                coord.x = 736.53; coord.y = 1659.90;
                                coordinates.push_back(coord);
                                coord.x = 679.01; coord.y = 1628.18;
                                coordinates.push_back(coord);
                                coord.x = 678.67; coord.y = 1628.01;
                                coordinates.push_back(coord);
                                coord.x = 590.98; coord.y = 1588.18;
                                coordinates.push_back(coord);
                                coord.x = 512.64; coord.y = 1545.63;
                                coordinates.push_back(coord);
                                coord.x = 496.63; coord.y = 1538.19;
                                coordinates.push_back(coord);
                                coord.x = 187.97; coord.y = 1405.39;
                                coordinates.push_back(coord);
                                coord.x = 70.41; coord.y = 1354.71;
                                coordinates.push_back(coord);
                                coord.x = 59.59; coord.y = 1346.48;
                                coordinates.push_back(coord);
                                coord.x = 47.97; coord.y = 1334.33;
                                coordinates.push_back(coord);
                                coord.x = 12.59; coord.y = 1273.02;
                                coordinates.push_back(coord);
                                coord.x = 7.18; coord.y = 1261.86;
                                coordinates.push_back(coord);
                                coord.x = 1.48; coord.y = 1250.11;
                                coordinates.push_back(coord);

                            }
                            else{
                                if(route == "YBTEntranceExit"){
                                    coord.x = -0.00; coord.y = -0.00;
                                    coordinates.push_back(coord);
                                    coord.x = 48.49; coord.y = 48.30;
                                    coordinates.push_back(coord);
                                    coord.x = 98.98; coord.y = 102.87;
                                    coordinates.push_back(coord);
                                    coord.x = 2101.10; coord.y = 2490.66;
                                    coordinates.push_back(coord);
                                    coord.x = 2101.87; coord.y = 2491.74;
                                    coordinates.push_back(coord);
                                    coord.x = 2148.46; coord.y = 2570.28;
                                    coordinates.push_back(coord);
                                    coord.x = 2158.19; coord.y = 2569.53;
                                    coordinates.push_back(coord);
                                    coord.x = 2161.70; coord.y = 2573.80;
                                    coordinates.push_back(coord);
                                    coord.x = 2161.70; coord.y = 2573.80;
                                    coordinates.push_back(coord);
                                    coord.x = 2310.84; coord.y = 2754.89;
                                    coordinates.push_back(coord);
                                    coord.x = 2310.84; coord.y = 2754.89;
                                    coordinates.push_back(coord);
                                    coord.x = 2370.98; coord.y = 2821.64;
                                    coordinates.push_back(coord);
                                    coord.x = 2370.98; coord.y = 2821.64;
                                    coordinates.push_back(coord);
                                    coord.x = 2433.16; coord.y = 2891.34;
                                    coordinates.push_back(coord);
                                    coord.x = 2439.07; coord.y = 2896.45;
                                    coordinates.push_back(coord);
                                    coord.x = 2494.74; coord.y = 2965.42;
                                    coordinates.push_back(coord);
                                    coord.x = 2543.85; coord.y = 3020.19;
                                    coordinates.push_back(coord);
                                    coord.x = 2600.18; coord.y = 3075.03;
                                    coordinates.push_back(coord);
                                    coord.x = 2600.18; coord.y = 3075.03;
                                    coordinates.push_back(coord);
                                    coord.x = 2644.96; coord.y = 3115.56;
                                    coordinates.push_back(coord);
                                    coord.x = 2677.18; coord.y = 3143.51;
                                    coordinates.push_back(coord);
                                    coord.x = 2701.88; coord.y = 3164.38;
                                    coordinates.push_back(coord);
                                    coord.x = 2727.60; coord.y = 3183.93;
                                    coordinates.push_back(coord);
                                    coord.x = 3206.34; coord.y = 3533.85;
                                    coordinates.push_back(coord);
                                    coord.x = 3227.91; coord.y = 3549.12;
                                    coordinates.push_back(coord);
                                    coord.x = 3250.67; coord.y = 3564.57;
                                    coordinates.push_back(coord);
                                    coord.x = 3273.17; coord.y = 3578.94;
                                    coordinates.push_back(coord);
                                    coord.x = 3296.16; coord.y = 3592.83;
                                    coordinates.push_back(coord);
                                    coord.x = 3317.33; coord.y = 3605.14;
                                    coordinates.push_back(coord);
                                    coord.x = 3338.51; coord.y = 3616.87;
                                    coordinates.push_back(coord);
                                    coord.x = 3361.09; coord.y = 3628.63;
                                    coordinates.push_back(coord);
                                    coord.x = 3385.87; coord.y = 3640.86;
                                    coordinates.push_back(coord);
                                    coord.x = 3408.12; coord.y = 3651.27;
                                    coordinates.push_back(coord);
                                    coord.x = 3430.27; coord.y = 3660.93;
                                    coordinates.push_back(coord);
                                    coord.x = 3453.86; coord.y = 3670.26;
                                    coordinates.push_back(coord);
                                    coord.x = 3479.56; coord.y = 3679.72;
                                    coordinates.push_back(coord);
                                    coord.x = 3507.29; coord.y = 3689.26;
                                    coordinates.push_back(coord);
                                    coord.x = 3535.69; coord.y = 3698.39;
                                    coordinates.push_back(coord);
                                    coord.x = 3565.62; coord.y = 3706.72;
                                    coordinates.push_back(coord);
                                    coord.x = 3596.43; coord.y = 3714.18;
                                    coordinates.push_back(coord);
                                    coord.x = 3626.76; coord.y = 3720.73;
                                    coordinates.push_back(coord);
                                    coord.x = 5070.52; coord.y = 3993.50;
                                    coordinates.push_back(coord);
                                    coord.x = 5133.15; coord.y = 4004.79;
                                    coordinates.push_back(coord);
                                    coord.x = 5193.44; coord.y = 4015.18;
                                    coordinates.push_back(coord);
                                    coord.x = 5263.07; coord.y = 4026.34;
                                    coordinates.push_back(coord);
                                    coord.x = 5320.54; coord.y = 4034.94;
                                    coordinates.push_back(coord);
                                    coord.x = 5381.68; coord.y = 4043.41;
                                    coordinates.push_back(coord);
                                    coord.x = 5585.95; coord.y = 4070.31;
                                    coordinates.push_back(coord);
                                }
                                else{
                                    if(route == "YBTExitEntrance"){
                                        coord.x = 5580.09; coord.y = 4109.36;
                                        coordinates.push_back(coord);
                                        coord.x = 5507.94; coord.y = 4101.56;
                                        coordinates.push_back(coord);
                                        coord.x = 5440.47; coord.y = 4093.77;
                                        coordinates.push_back(coord);
                                        coord.x = 5376.07; coord.y = 4085.79;
                                        coordinates.push_back(coord);
                                        coord.x = 5314.40; coord.y = 4077.25;
                                        coordinates.push_back(coord);
                                        coord.x = 5256.47; coord.y = 4068.57;
                                        coordinates.push_back(coord);
                                        coord.x = 5186.38; coord.y = 4057.34;
                                        coordinates.push_back(coord);
                                        coord.x = 5125.67; coord.y = 4046.88;
                                        coordinates.push_back(coord);
                                        coord.x = 5062.70; coord.y = 4035.53;
                                        coordinates.push_back(coord);
                                        coord.x = 3618.22; coord.y = 3762.62;
                                        coordinates.push_back(coord);
                                        coord.x = 3586.82; coord.y = 3755.84;
                                        coordinates.push_back(coord);
                                        coord.x = 3554.77; coord.y = 3748.09;
                                        coordinates.push_back(coord);
                                        coord.x = 3523.32; coord.y = 3739.33;
                                        coordinates.push_back(coord);
                                        coord.x = 3493.69; coord.y = 3729.80;
                                        coordinates.push_back(coord);
                                        coord.x = 3465.11; coord.y = 3719.97;
                                        coordinates.push_back(coord);
                                        coord.x = 3438.49; coord.y = 3710.18;
                                        coordinates.push_back(coord);
                                        coord.x = 3413.73; coord.y = 3700.38;
                                        coordinates.push_back(coord);
                                        coord.x = 3390.39; coord.y = 3690.19;
                                        coordinates.push_back(coord);
                                        coord.x = 3367.22; coord.y = 3679.37;
                                        coordinates.push_back(coord);
                                        coord.x = 3341.60; coord.y = 3666.72;
                                        coordinates.push_back(coord);
                                        coord.x = 3318.13; coord.y = 3654.49;
                                        coordinates.push_back(coord);
                                        coord.x = 3296.08; coord.y = 3642.27;
                                        coordinates.push_back(coord);
                                        coord.x = 3274.21; coord.y = 3629.56;
                                        coordinates.push_back(coord);
                                        coord.x = 3250.44; coord.y = 3615.21;
                                        coordinates.push_back(coord);
                                        coord.x = 3226.99; coord.y = 3600.22;
                                        coordinates.push_back(coord);
                                        coord.x = 3203.38; coord.y = 3584.19;
                                        coordinates.push_back(coord);
                                        coord.x = 3181.21; coord.y = 3568.49;
                                        coordinates.push_back(coord);
                                        coord.x = 2702.21; coord.y = 3218.39;
                                        coordinates.push_back(coord);
                                        coord.x = 2702.21; coord.y = 3218.39;
                                        coordinates.push_back(coord);
                                        coord.x = 2685.23; coord.y = 3205.00;
                                        coordinates.push_back(coord);
                                        coord.x = 2669.02; coord.y = 3191.36;
                                        coordinates.push_back(coord);
                                        coord.x = 2652.53; coord.y = 3176.58;
                                        coordinates.push_back(coord);
                                        coord.x = 2636.98; coord.y = 3161.88;
                                        coordinates.push_back(coord);
                                        coord.x = 2636.98; coord.y = 3161.88;
                                        coordinates.push_back(coord);
                                        coord.x = 2622.07; coord.y = 3147.08;
                                        coordinates.push_back(coord);
                                        coord.x = 2608.58; coord.y = 3133.13;
                                        coordinates.push_back(coord);
                                        coord.x = 2591.96; coord.y = 3115.41;
                                        coordinates.push_back(coord);
                                        coord.x = 2576.01; coord.y = 3097.39;
                                        coordinates.push_back(coord);
                                        coord.x = 2561.17; coord.y = 3079.65;
                                        coordinates.push_back(coord);
                                        coord.x = 2548.04; coord.y = 3063.17;
                                        coordinates.push_back(coord);
                                        coord.x = 2535.51; coord.y = 3046.43;
                                        coordinates.push_back(coord);
                                        coord.x = 2523.14; coord.y = 3029.43;
                                        coordinates.push_back(coord);
                                        coord.x = 2389.50; coord.y = 2846.83;
                                        coordinates.push_back(coord);
                                        coord.x = 2385.10; coord.y = 2846.29;
                                        coordinates.push_back(coord);
                                        coord.x = 2366.94; coord.y = 2824.08;
                                        coordinates.push_back(coord);
                                        coord.x = 2366.94; coord.y = 2824.08;
                                        coordinates.push_back(coord);
                                        coord.x = 2323.68; coord.y = 2773.40;
                                        coordinates.push_back(coord);
                                        coord.x = 2323.68; coord.y = 2773.40;
                                        coordinates.push_back(coord);
                                        coord.x = 2309.76; coord.y = 2757.09;
                                        coordinates.push_back(coord);
                                        coord.x = 2309.76; coord.y = 2757.09;
                                        coordinates.push_back(coord);
                                        coord.x = 2198.64; coord.y = 2621.58;
                                        coordinates.push_back(coord);
                                        coord.x = 2198.64; coord.y = 2621.58;
                                        coordinates.push_back(coord);
                                        coord.x = 2160.89; coord.y = 2578.67;
                                        coordinates.push_back(coord);
                                        coord.x = 2156.28; coord.y = 2576.05;
                                        coordinates.push_back(coord);
                                        coord.x = 281.40; coord.y = 339.02;
                                        coordinates.push_back(coord);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }


}

//Calcular menor distancia ponto reta http://stackoverflow.com/questions/12132352/distance-from-a-point-to-a-line-segment
//http://stackoverflow.com/questions/3120357/get-closest-point-to-a-line
//Thanks for Paul Bourke http://paulbourke.net/geometry/pointlineplane/
//FIXME Calculate in 3D Space anyway.

double MapMatching::Magnitude( Coord *A, Coord *B )
{
    //std::cout << *A << *B << endl;
    return sqrt( ( (B->x - A->x) * (B->x - A->x) ) + ((B->y - A->y) * (B->y - A->y) ) );
}

int MapMatching::DistancePointLine(Coord *A, Coord *B, Coord *P, Coord *intersection, double *distance){

    //std::cout << *A << *B << *P <<"\n\n";

    double magnitude;
    double U;
    magnitude = Magnitude(A,B);

    U = ( ( (P->x - A->x) * (B->x - A->x) ) +
          ( (P->y - A->y) * (B->y - A->y) ) )
        / (magnitude * magnitude);

    //std::cout << U <<"****\n";

    if( U < (double) 0.0 || U > (double) 1.0){
        return 0; //closest point does not fall within the line segment
    }

    intersection->x = A->x + U * (B->x - A->x);
    intersection->y = A->y + U * (B->y - A->y);
    intersection->z = A->z;

    *distance = Magnitude(P,intersection);

    return 1; //lies at the intersection point and with distance
}


void MapMatching::DoMapMatching(const Coord& pGPS){
    uint i;
    Coord A, B, P;

    for(i=1; i < coordinates.size(); i++){
        A = coordinates.at(i-1);
        A.z = pGPS.z;
        B = coordinates.at(i);
        B.z = pGPS.z;
        P = pGPS;
        if( DistancePointLine( &A, &B, &P, &matchPoint, &distGPSMM) ){
            //std::cout << "MM!\n\n";
            //std::cout << matchPoint <<'\t'<< pGPS << endl;

            break;
        }
    }
}

MapMatching::~MapMatching() {
    // TODO Auto-generated destructor stub
}

} /* namespace Localization */
